input_select:
  studio_scene:
    name: Studio Scene
    options:
      - "Full Bright"
      - "Late Night"
      - "All Auto"
      - "Lamps Auto"

automation:
  - alias: "Studio Scene Controller"
    id: studio_scene_controller
    trigger:
      - platform: state
        entity_id: input_select.studio_scene
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.studio_scene
                state: "Full Bright"
            sequence:
              - service: script.studio_full_bright
          - conditions:
              - condition: state
                entity_id: input_select.studio_scene
                state: "Late Night"
            sequence:
              - service: script.studio_late_night
          - conditions:
              - condition: state
                entity_id: input_select.studio_scene
                state: "All Auto"
            sequence:
              - service: script.studio_all_auto
          - conditions:
              - condition: state
                entity_id: input_select.studio_scene
                state: "Lamps Auto"
            sequence:
              - service: script.studio_lamps_auto

script:
  studio_full_bright:
    alias: "studio_full_bright"
    use_blueprint:
      path: homeassistant/lighting_scene_controller.yaml
      input:
        zone_name: studio
        light_pool:
          label_id: studio_lights_pool
        lights_on:
          - light.studio_ceiling
          - light.studio_lamps
        override_enabled: true
        override_brightness: 100
        override_temperature: 3500
  studio_late_night:
    alias: "studio_late_night"
    use_blueprint:
      path: homeassistant/lighting_scene_controller.yaml
      input:
        zone_name: studio
        light_pool:
          label_id: studio_lights_pool
        lights_on:
          - light.studio_lamps
        override_enabled: true
        override_brightness: 50
        override_temperature: 2000
  studio_all_auto:
    alias: "studio_all_auto"
    use_blueprint:
      path: homeassistant/lighting_scene_controller.yaml
      input:
        zone_name: studio
        light_pool:
          label_id: studio_lights_pool
        lights_on:
          - light.studio_ceiling
          - light.studio_lamps
        override_enabled: false
  studio_lamps_auto:
    alias: "studio_lamps_auto"
    use_blueprint:
      path: homeassistant/lighting_scene_controller.yaml
      input:
        zone_name: studio
        light_pool:
          label_id: studio_lights_pool
        lights_on:
          - light.studio_lamps
        override_enabled: false
